<a href="https://colab.research.google.com/github/rameshver43/Practice/blob/master/Deep_Learning_for_computer_vision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors: Are Multi Dimensional Arrays



Array: is an ordered arrangement of numbers

0-D single element=> ex 8

[2 0 -3]  1-D array (1-D tensor)  shape=(3,)

2-D Tensor  
[1 2 0, 3 5 0]
shape= (2,3)

3-D Tensor
[[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]
shape = (2,2,3)


In [2]:
import tensorflow as tf

In [6]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [8]:
tensor_one_d = tf.constant([2,0,-3])
print(tensor_one_d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [9]:
tensor_two_d = tf.constant([
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ])

print(tensor_two_d)


tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)


In [10]:
tensor_three_d = tf.constant([[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ],[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ]])

print(tensor_three_d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]
  [ 1  5  6]
  [ 2  3  8]]

 [[ 1  2  0]
  [ 3  5 -1]
  [ 1  5  6]
  [ 2  3  8]]], shape=(2, 4, 3), dtype=int32)


In [12]:
print(tensor_three_d.ndim)  # no of dim

3


In [13]:
print(tensor_three_d.shape)

(2, 4, 3)


In [14]:
tensor_four_d = tf.constant([[[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ],[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ]],[[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ],[
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ]]])

print(tensor_four_d)

tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]

  [[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]]


 [[[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]

  [[ 1  2  0]
   [ 3  5 -1]
   [ 1  5  6]
   [ 2  3  8]]]], shape=(2, 2, 4, 3), dtype=int32)


In [20]:
tensor_one_d1 = tf.constant([2,0.4,-3,8,90],dtype=tf.float32)
print(tensor_one_d1)
casted_tensor_one_d = tf.cast(tensor_one_d1,dtype=tf.int16)
print(casted_tensor_one_d)

tf.Tensor([ 2.   0.4 -3.   8.  90. ], shape=(5,), dtype=float32)
tf.Tensor([ 2  0 -3  8 90], shape=(5,), dtype=int16)


In [22]:
tensor_string = tf.constant(["Hello world","Hi"])
print(tensor_string)

tf.Tensor([b'Hello world' b'Hi'], shape=(2,), dtype=string)


In [23]:
import numpy as np

In [24]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [25]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int64)


https://www.tensorflow.org/api_docs/python/tf/

In [35]:
eye_tensor = tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[2,4],
    dtype=tf.dtypes.float32,
    name=None
)

print(eye_tensor)  #identity metrix

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]], shape=(2, 4, 5, 5), dtype=float32)


In [36]:
fill_tensor = tf.fill([3, 4], 5,name=None)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [42]:
ones_tensor =tf.ones(
    [3,5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(3, 5, 3), dtype=float32)


In [40]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
one_like_tensor =tf.ones_like(
    tensor, dtype=None, name=None
)
print(one_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [43]:
zeros_tensor = tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [47]:
zeros_tensor_shape=tf.shape(
    zeros_tensor,
    out_type=tf.dtypes.int32,
    name=None
)

print(zeros_tensor_shape)

tf.Tensor([3 2], shape=(2,), dtype=int32)


In [48]:
# shape of tensor 't' is [2, 2, 3]
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.rank(t)  # 3

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [50]:
t = tf.constant([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
tf.size(t)
#Returns a 0-D Tensor representing the number of elements in input of type out_type. Defaults to tf.int32.

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [53]:
random_tensor = tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0, 
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[101.45999   99.79752 ]
 [ 99.82898  100.11639 ]
 [ 98.010414  99.05498 ]], shape=(3, 2), dtype=float32)


In [62]:
random_tensor = tf.random.uniform(
    [5,5],
    minval=2,
    maxval=10000,
    dtype=tf.dtypes.int32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[1487 8607 3259 3410 4006]
 [4389 9420 4594 4521 3468]
 [8860 2221 1650 8645 4293]
 [ 147 5903 8718 3796 2059]
 [3011 5137  295 9474 9105]], shape=(5, 5), dtype=int32)


In [63]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))


tf.Tensor([2 0 1 2 1], shape=(5,), dtype=int32)
tf.Tensor([1 2 2 0 2], shape=(5,), dtype=int32)


In [65]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))
print(tf.random.uniform(shape=[5], maxval=3, dtype=tf.int32, seed=10))

tf.Tensor([2 0 1 2 1], shape=(5,), dtype=int32)
tf.Tensor([1 2 2 0 2], shape=(5,), dtype=int32)


**Tensor Indexing**

In [3]:
tensor_indexed  = tf.constant([3,6,1,2,3])
print(tensor_indexed)

tf.Tensor([3 6 1 2 3], shape=(5,), dtype=int32)


In [13]:
print(tensor_indexed[0:4])
print(tensor_indexed[1:5:1])

tf.Tensor([3 6 1 2], shape=(4,), dtype=int32)
tf.Tensor([6 1 2 3], shape=(4,), dtype=int32)


In [8]:
tf.range(2,6)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5], dtype=int32)>

In [17]:
tensor_two_d = tf.constant([
    [1,2,0],
     [3,5,-1],
      [1,5,6],
       [2,3,8]
    ])

print(tensor_two_d[0:3,:])
print(tensor_two_d[:,1])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]], shape=(3, 3), dtype=int32)
tf.Tensor([2 5 5 3], shape=(4,), dtype=int32)


**Tensorflow Math**

https://www.tensorflow.org/api_docs/python/tf/math

In [18]:
x_abs = tf.constant([-2.25,3.25])
tf.abs(x_abs)


<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [21]:
x =tf.constant([3+4j,2+3j])
tf.abs(x)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([5.        , 3.60555128])>

In [31]:
x = tf.constant([[4.0], [16.0]])
tf.sqrt(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [4.]], dtype=float32)>

In [34]:
x = tf.constant([1,2,3])
y = tf.constant([1])
tf.add(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4], dtype=int32)>

In [42]:
x = tf.constant([4.0])
print(x.shape)
print(tf.math.argmin(x))
print(tf.math.argmax(x))

(1,)
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(0, shape=(), dtype=int64)
